command_timeout = 2000

add_newline = true

# format = '$username@$hostname$all'

format = """
$username\
$hostname\
$shlvl\
$singularity\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$deno\
$dotnet\
$nodejs\
$perl\
$python\
$terraform\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$directory\
$character"""


[time]
format = '[$time]($style) '
time_format = '%H:%M'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_symbol = '.../'

[git_branch]
truncation_length = 20

[git_commit]
tag_disabled = false
commit_hash_length = 7
disabled = false

[package]
disabled = false

[status]
format = '[$status]($style) '
disabled = false

[aws]
disabled = true

[username]
show_always = true
format = '[$user]($style)'
disabled = false

[hostname]
format='[$ssh_symbol$hostname]($style)'
ssh_only = false
disabled = false
