command_timeout = 2000

add_newline = true

format = '$username@$hostname$all'

[time]
format = '[$time]($style) '
time_format = '%H:%M'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_symbol = '.../'

[git_branch]
truncation_length = 20

[git_commit]
tag_disabled = false
commit_hash_length = 7
disabled = false

[memory_usage]
format = 'using [$ram_pct RAM]($style) '
disabled = false

[package]
disabled = true

[status]
format = '[$status]($style) '
disabled = false

[aws]
disabled = true

[username]
show_always = true
format = '[$user]($style)'
disabled = false

[hostname]
show_always = true
ssh_only = false
disabled = false
